[package]
name = "tiaoshi-dashi-qemu-sbi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustsbi = "0.2.0-alpha.3"